### ISSUE TITLE
Support for Styled Components?

### ISSUE THREAD

**Issue by phyllisstein** [atom/language-typescript#10]
The [`language-babel`](https://github.com/gandm/language-babel) package for Atom includes special highlighting rules that support [Styled Components](https://www.styled-components.com/), highlighting tagged template literals starting with `styled` as CSS:

![screenshot](https://user-images.githubusercontent.com/2207980/32012637-82e97b08-b986-11e7-8e80-e23cbf1eeaf7.png)

Are there any plans for similar support in `language-typescript`? What would the path to that kind of support look like? Happy to try for a PR if there's a wish for it.

**Comment by damieng** [comment]
I want to make sure this package doesn't diverge from the upstream work it is based on as the maintenance cost goes right up.

If this could be done without modifying the existing two grammar files we get from the upstream repository (maintained by Microsoft) then we might consider it.

**Comment by phyllisstein** [comment]
That makes total sense. Thanks for responding so quickly and thoughtfully! I'll try playing around a little and see if there's anything that can be done.

**Comment by zaynv** [comment]
Is it still not possible to add support for this? I see that VSCode seems to have support for this
