### ISSUE TITLE
Code folding in typescript files

### ISSUE THREAD

**Issue by pstahmer** [atom/language-typescript#17]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

In typescript files code folding seems to be buggy when a foldable block is preceded by comments. Specifically it will fold the comment line, and hide the next line down from that regardless of what that line is. Also it will not permit any line directly below a comment line to be folded. 

This does not occur for regular javascript files so I hope this is the appropriate project to log this bug on. If not please let me know and I'll close this issue in favor of one on the correct repo. 

### Steps to Reproduce

1. Open a new file and set the file type to Typescript
2. Create a function with a comment line above it. I used 
```
// test
test() {
  ...
}

/* 
  test
*/
test() {
  ...
}

// test1
// test2
// test3
test() {
  
}
```

**Expected behavior:**
1. Foldable lines should be: 2, 6, 9, 13, 16
2. Folding 13 should hide 14, 15

**Actual behavior:** 
1. Foldable lines are: 1, 6, 9, 13
2. Folding 1 should not hide 2
3. Folding 13 hides 14, 15, 16

**Reproduces how often:** Always, even in safe mode.

### Versions

```Atom    : 1.23.2
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
```
```
macOs High Sierra
Version 10.13.1
```

### Additional Information
Unfolded, showing foldable lines
![Unfolded, showing foldable lines](https://user-images.githubusercontent.com/4052220/35063240-26302b58-fb8c-11e7-8405-3d2ff86e7313.png)
Folded
![Folded](https://user-images.githubusercontent.com/4052220/35063241-26484a4e-fb8c-11e7-81be-0c101758ccef.png)

**Comment by lierdakil** [comment]
Atom folds code on indentation. That's it. With Atom 1.25, you can use experimental [tree-sitter](https://github.com/tree-sitter/tree-sitter) grammars that should handle folding better (see the [blog post](http://blog.atom.io/2018/03/15/atom-1-25.html#improved-syntax-highlighting-and-code-folding) for more information)

**Comment by damieng** [comment]
This will be improved when we get a TypeScript grammar for tree-sitter.

**Comment by damieng** [comment]
Sorry, my correction - we *have* a TypeScript grammar for tree-sitter and the cold folding should already be massively improved there if you turn it on as @lierdakil suggests.

**Comment by pstahmer** [comment]
Thanks guys, I'll give that a shot

**Comment by pstahmer** [comment]
It doesn't look like tree-sitter fixes typescript's issues with comment blocks preceding foldable blocks. I'm now on 1.25.0 and still seeing the same behavior shown in the images attached to the original post. This also still only applies to typescript files.

**Comment by damieng** [comment]
I think that issue should probably then be filed over at https://github.com/tree-sitter/tree-sitter-typescript so the right people see it.

**Comment by pstahmer** [comment]
I can post it there, but given that the issue occurred both before and after the tree-sitter updates, and that it is regarding the presence of folding arrows just as much as the actual fold behavior, it doesn't seem like the right place to me.

**Comment by lierdakil** [comment]
Did you actually enable tree-sitter? Settings -> Core -> Use Tree Sitter Parsers:
![image](https://user-images.githubusercontent.com/7275622/37799318-711bd3de-2e30-11e8-993b-f75f30b5dc4a.png)

**Comment by pstahmer** [comment]
Yes I have that enabled

**Comment by lierdakil** [comment]
Then make sure you're using Atom's builtin typescript grammar (specifically, 'TypeScript', and *not* 'TypeScriptReact'), and not a third-party one. Because folding looks fine to me:
![image](https://user-images.githubusercontent.com/7275622/37799635-592915c4-2e31-11e8-90f1-1438ef2e12db.png)![image](https://user-images.githubusercontent.com/7275622/37799648-64c44aa2-2e31-11e8-959a-572759075f88.png)

**Comment by pstahmer** [comment]
Hmmm I think I stand corrected. Looks like it works now, but only after I set the types on all open files again. I'll just close all open panes. Sorry about that, I probably should have done so before posting again.
