### ISSUE TITLE
Package snippets don't work

### ISSUE THREAD

**Issue by Jorys-Paulin** [atom/language-typescript#40]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

The snippets for the typescript language don't work. Their neither show up in the autocomplete dialog, or when hitting `Tab` after typing them.
This issue happens whether or not the file is saved, and whether or not your're running Atom vanilla (or in safe mode) or with additional packages. I do not have the `atom-typescript` package installed.

### Steps to Reproduce

1. Open Atom
2. Create a new TypeScript file and save it
3. Start typing `class`, which according to the [snippets file](https://github.com/atom/language-typescript/blob/master/snippets/TypeScript.json#L16), should complete with a class definition

**Expected behavior:**

- The autocomplete dialog is supposed to show up
- After typing `class`, the snippet is supposed to autocomplete

**Actual behavior:**

- The autocomplete dialog doesn't show up
- Hitting `Tab` after typing `class` just adds a space

**Reproduces how often:**

This issues happens everytime, on normal Atom or when in safe mode

### Versions

- Atom:
```
Atom    : 1.40.1
Electron: 3.1.10
Chrome  : 66.0.3359.181
Node    : 10.2.0
```
- APM:
```
apm  2.4.3
npm  6.2.0
node 10.2.1 x64
atom 1.40.1
python 2.7.15
git 2.22.0.windows.1
visual studio 2015
```

I'm running Windows 10 version 1903 / 18362.356

### Additional Information
I've forked this repository and added a file called `language-typescript.cson` inside the `snippets` directory with the same contents as the [language-javascript.cson](https://github.com/atom/language-javascript/blob/master/snippets/language-javascript.cson) file from the `language-javascript` package, edited the first line from `'.source.js, .source.flow'` to `'.source.ts, .source.tsx'` and the snippets worked again.

However, **I also changed the `body` part of each snippet in the JSON files to be strings instead of arrays of strings, and the snippets worked again**. I think that's what causing the issue here.

**Comment by rsese** [comment]
Thanks for the report and the additional details - reproduced with 1.42.0-nightly6 on macOS 10.14.6 (running `Snippets: Available` from the command palette show none of the Typescript snippets) .  Looks like the snippets were added a while ago and haven't been touched since so I wonder if this worked before or not, confirmed that snippets didn't seem to work back to 1.36.1 as well.

**Comment by rsese** [comment]
> However, **I also changed the `body` part of each snippet in the JSON files to be strings instead of arrays of strings, and the snippets worked again**. I think that's what causing the issue here.

We chatted about this today and think this would be a good fix - would you be up for making a pull request for this?  No pressure, just wanted to check with you since you did the leg work :smile:

**Comment by Jorys-Paulin** [comment]
Sure, but I'm not sure if I should include the snippets from javascript as well. I haven't found any way to tell Atom to "include" snippets from javascript. This would be nice because all Javascript snippets aren't included.
I've pushed a [commit on my fork](https://github.com/Jorys-Paulin/language-typescript/commit/05dd748a74e4203ec3ffba0bffb4e41818a3813b) that moves the old JSON files to one CSON with the arrays replaced by the multi-line syntax suggested by the Flight Manual. This seems to fix the problem.
Maybe I should add more snippets from javascript before making a pull request?

**Comment by rsese** [comment]
Thanks for asking about that - we're not making or accepting changes to what default snippets are provided in the language repositories right now (unless a snippet produces invalid code) since people can easily add their own snippets.  So to resolve this specific issue, let's keep the change to just fixing the problem with the existing snippets.

**Comment by Jorys-Paulin** [comment]
I've opened a pull request with my current changes. This is my first PR to the project, so I might get some things wrong.

**Comment by rsese** [comment]
Great thanks @Jorys-Paulin :v:  We can't promise a timeframe for when someone will take a look, but if there are any issues, whoever reviews will let you know.
