### ISSUE TITLE
export as default marked as syntax--invalid

### ISSUE THREAD

**Issue by rr-kalbeck** [atom/language-typescript#6]
![image](https://user-images.githubusercontent.com/32479606/31448786-94dc8ad0-aea5-11e7-844c-9b4543e45c04.png)

**Comment by damieng** [comment]
The actual syntax grammar comes from https://github.com/Microsoft/TypeScript-TmLanguage which is doing this intentionally for whatever reason as shown at https://github.com/Microsoft/TypeScript-TmLanguage/blob/master/TypeScript.tmLanguage#L2736

 I'd suggest filing an issue there and we'll pickup the changes.

**Comment by rr-kalbeck** [comment]
ok thanks, i'll do that.

**Comment by rr-kalbeck** [comment]
https://github.com/Microsoft/TypeScript-TmLanguage/issues/531
